name: Build and Push Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/hareeen/hareen.io

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      # Generate tags and OCI labels
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # keep :latest for humans (don’t rely on it for automation)
            type=raw,value=latest
            # monotonically increasing SemVer for Flux semver policy
            type=raw,value=v0.0.${{ github.run_number }}
            # commit traceability
            type=sha,format=short,prefix=sha-
            # lexicographically sortable timestamp (UTC)
            type=raw,value=ts-{{date 'YYYYMMDDHHmmss'}}
          labels: |
            org.opencontainers.image.title=hareen.io
            org.opencontainers.image.description=hareen.io application image
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ssZ'}}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
