name: Deploy Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deployment.yml
  workflow_run:
    workflows:
      - Build and Push Image
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_TAG: ghcr.io/hareeen/hareen.io:latest

jobs:
  push:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ env.DOCKER_TAG }}
            docker stop hareen.io || true
            docker rm hareen.io || true
            docker run -d --name hareen.io -p 7101:3000 --restart always ${{ env.DOCKER_TAG }}
